name: pos_printer_d
description: A clean Flutter plugin for POS thermal printers. Supports Bluetooth, USB, and Network (TCP) connections with a simple unified API.
version: 1.0.1
homepage: https://github.com/alexdlov/pos_printer
repository: https://github.com/alexdlov/pos_printer
issue_tracker: https://github.com/alexdlov/pos_printer/issues

topics:
  - printer
  - pos
  - thermal-printer
  - bluetooth
  - esc-pos

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  network_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pos_printer
        pluginClass: PosPrinterPlugin
      ios:
        pluginClass: PosPrinterPlugin
      windows:
        pluginClass: PosPrinterPluginCApi
